name: wren
services:
#  bootstrap:
#    command:
#      - /bin/sh
#      - /app/init.sh
#    environment:
#      DATA_PATH: /app/data
#      PG_PASSWORD: wren-pg-password-placeholder
#      PG_USERNAME: wren-user-placeholder
#    image: ghcr.io/canner/wren-bootstrap:0.1.4
#    networks:
#      default: null
#    platform: linux/amd64
#    restart: on-failure
#    volumes:
#      - type: volume
#        source: data
#        target: /app/data
#        volume: {}
#  postgres:
#    environment:
#      PGDATA: /var/lib/postgresql/data/pgdata
#      POSTGRES_DB: test
#      POSTGRES_PASSWORD: secret
#      POSTGRES_USER: test
#    image: postgres:14-alpine
#    networks:
#      default: null
#    platform: linux/amd64
#    ports:
#      - mode: ingress
#        target: 5432
#        published: "9432"
#        protocol: tcp
#    volumes:
#      - type: volume
#        source: data
#        target: /var/lib/postgresql/data
#        volume: {}
  qdrant:
    ports:
    - 6333:6333
    - 6334:6334
    image: qdrant/qdrant:v1.7.4
    restart: on-failure
    volumes:
      - /tmp/data:/qdrant/storage
        #  wren-ai-service:
        #    depends_on:
        #      qdrant:
        #        condition: service_started
        #        required: true
        #    environment:
        #      OPENAI_API_KEY: sk-empty
        #      OPENAI_GENERATION_MODEL: gpt-4o
        #      PYTHONUNBUFFERED: "1"
        #      QDRANT_HOST: qdrant
        #      WREN_AI_SERVICE_PORT: "5555"
        #      WREN_ENGINE_ENDPOINT: http://host.docker.internal:8080
        #    expose:
        #      - "5555"
        #    image: ghcr.io/canner/wren-ai-service:0.3.7
        #    platform: linux/amd64
        #    ports:
        #      - mode: ingress
        #        target: 5555
        #        published: "5555"
        #        protocol: tcp
        #    restart: on-failure
#  wren-engine:
#    depends_on:
#      bootstrap:
#        condition: service_started
#        required: true
#    expose:
#      - "8080"
#      - "7432"
#    image: wren-engine:0.4.5-SNAPSHOT-arm64
#    networks:
#      wren: null
#    restart: always
#    volumes:
#      - type: volume
#        source: data
#        target: /usr/src/app/etc
#        volume: {}
#  wren-ui:
#    environment:
#      DB_TYPE: sqlite
#      NEXT_PUBLIC_POSTHOG_API_KEY: phc_nhF32aj4xHXOZb0oqr2cn4Oy9uiWzz6CCP4KZmRq9aE
#      NEXT_PUBLIC_POSTHOG_HOST: https://app.posthog.com
#      NEXT_PUBLIC_TELEMETRY_ENABLED: "true"
#      NEXT_PUBLIC_USER_UUID: ""
#      OPENAI_GENERATION_MODEL: gpt-3.5-turbo
#      PG_PASSWORD: wren-pg-password-placeholder
#      PG_USERNAME: wren-user-placeholder
#      POSTHOG_API_KEY: phc_nhF32aj4xHXOZb0oqr2cn4Oy9uiWzz6CCP4KZmRq9aE
#      POSTHOG_HOST: https://app.posthog.com
#      SQLITE_FILE: /app/data/db.sqlite3
#      TELEMETRY_ENABLED: "true"
#      USER_UUID: ""
#      WREN_AI_ENDPOINT: http://localhost:5555
#      WREN_AI_SERVICE_VERSION: 0.3.7
#      WREN_ENGINE_ENDPOINT: http://localhost:8080
#      WREN_ENGINE_PORT: "8080"
#      WREN_PRODUCT_VERSION: 0.3.4
#      WREN_UI_VERSION: 0.5.6
#    image: wren-ui:local-arm64
#    networks:
#      default: null
#    ports:
#      - mode: ingress
#        target: 3000
#        published: "3000"
#        protocol: tcp
#    restart: always
#    volumes:
#      - type: volume
#        source: data
#        target: /app/data
#        volume: {}
#networks:
#  default:
#    name: wren_default
#  wren:
#    name: wren_wren
#    driver: bridge
volumes:
  data:
    name: wren_data
